create table news
(
    id int GENERATED BY DEFAULT AS IDENTITY primary key,
    name varchar(30) null,
    short_description varchar(30) null,
	description varchar(150) null
);

create table type (
    id int GENERATED BY DEFAULT AS IDENTITY primary key,
    type_name varchar(20) null,
	type_color varchar(15) null
);

create table news_types
(
    news_id int not null,
    type_id int not null,
	foreign key (news_id) references news (id),
    foreign key (type_id) references type (id)
);
